name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        symfony-versions: ['^4.4', '^5.4', '^6.4', '^7.2']
        php-versions: ['8.4', '8.3', '8.2', '8.1', '8.0', '7.4', '7.3']
        # Exclude combinations that are not installable.
        exclude:
          - symfony-versions: '^6.4'
            php-versions: '7.3'
          - symfony-versions: '^6.4'
            php-versions: '7.4'
          - symfony-versions: '^7.2'
            php-versions: '7.3'
          - symfony-versions: '^7.2'
            php-versions: '7.4'
          - symfony-versions: '^7.2'
            php-versions: '8.0'

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}

      - name: Update Symfony
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          command: require
          args: symfony/symfony:${{ matrix.symfony-versions }} -W

      - name: PHPCS
        run: ./vendor/bin/phpcs ./src

      - name: PHPStan
        run: ./vendor/bin/phpstan analyse ./src

      - name: PHPUnit
        run: ./vendor/bin/phpunit